# Generated by Django 5.2 on 2025-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_siteinfo_email_siteinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=20, unique=True)),
                ('url', models.URLField(verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Соцмережа',
                'verbose_name_plural': 'Соцмережі',
            },
        ),
    ]
