# Generated by Django 5.2 on 2025-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAndPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Доставка та оплата', max_length=200, verbose_name='Заголовок сторінки')),
                ('content', models.TextField(help_text='Можна використовувати HTML', verbose_name='Контент сторінки (HTML або текст)')),
            ],
            options={
                'verbose_name': 'Сторінка доставки та оплати',
                'verbose_name_plural': 'Сторінка доставки та оплати',
            },
        ),
    ]
