# Generated by Django 5.2 on 2025-05-15 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+380000000000', help_text='У форматі +380XXXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефону має бути у форматі: +380XXXXXXXXX (9 цифр після +380).', regex='^\\+380\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовивіз'), ('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта')], default='pickup', max_length=20),
        ),
    ]
