# Generated by Django 5.2 on 2025-05-15 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_phone_number_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='У форматі +380XXXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути у форматі: '+380XXXXXXXXX' (9 цифр після +380).", regex='^\\+380\\d{9}$')]),
        ),
    ]
