# Generated by Django 5.2 on 2025-05-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('processing', 'Обробляється'), ('shipped', 'Відправлено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
