# Generated by Django 5.2 on 2025-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка категорії')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL (slug)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
