# Generated by Django 5.2 on 2025-05-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Скорочення')),
            ],
            options={
                'verbose_name': 'Одиниця вимірювання',
                'verbose_name_plural': 'Одиниці вимірювання',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва підкатегорії')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL (slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/', verbose_name='Картинка підкатегорії')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL (slug)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Колір')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Розмір')),
                ('available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory', verbose_name='Підкатегорія')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.unitofmeasurement', verbose_name='Одиниця вимірювання')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Колір')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Розмір')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.unitofmeasurement', verbose_name='Одиниця вимірювання')),
            ],
            options={
                'verbose_name': 'Варіант товару',
                'verbose_name_plural': 'Варіанти товарів',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
