# Generated by Django 5.2 on 2025-05-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_available_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='Має варіанти'),
        ),
    ]
