# Generated by Django 5.2 on 2025-05-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='unit_of_measurement',
        ),
    ]
