# Generated by Django 5.2 on 2025-05-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
